services:
  - type: web
    name: monika-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python telegram_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: BOT_TOKEN
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: XAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
